name: Build Telegram APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-35" \
                     "build-tools;35.0.0" \
                     "ndk;27.2.12479018" \
                     "cmake;3.10.2.4988404"

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew :TMessagesProj_App:assembleAfatDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Debug
          path: TMessagesProj_App/build/outputs/**/*.apk
